title: <p align="center"> Rugved Raorane </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rugved-raorane-55821729a//">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  
  <br>
  </p>



theme: jekyll-theme-minimal
